// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNixlZ23ed2qZ9_TyMyMDBQCNPOjdzB68',
    appId: '1:410375819014:web:606f215636d8ab42d3d887',
    messagingSenderId: '410375819014',
    projectId: 'workoutzzang-9b6f7',
    authDomain: 'workoutzzang-9b6f7.firebaseapp.com',
    storageBucket: 'workoutzzang-9b6f7.firebasestorage.app',
    measurementId: 'G-814T72LNEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-oCQ4r-kEYZXeUnS8d4ypTila10g6VxM',
    appId: '1:410375819014:android:8cf0d3aa028cba69d3d887',
    messagingSenderId: '410375819014',
    projectId: 'workoutzzang-9b6f7',
    storageBucket: 'workoutzzang-9b6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JHkdg4sPaSobe7U3ySrBJlNy6WZpPTk',
    appId: '1:410375819014:ios:e4ba87957696aadad3d887',
    messagingSenderId: '410375819014',
    projectId: 'workoutzzang-9b6f7',
    storageBucket: 'workoutzzang-9b6f7.firebasestorage.app',
    androidClientId: '410375819014-0ca6g3dq498tqb6mqacru68lpb8pv5h5.apps.googleusercontent.com',
    iosClientId: '410375819014-5tv371sd0ib3h84ka1q1movmmv7e6a17.apps.googleusercontent.com',
    iosBundleId: 'com.example.routinecareproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JHkdg4sPaSobe7U3ySrBJlNy6WZpPTk',
    appId: '1:410375819014:ios:e4ba87957696aadad3d887',
    messagingSenderId: '410375819014',
    projectId: 'workoutzzang-9b6f7',
    storageBucket: 'workoutzzang-9b6f7.firebasestorage.app',
    androidClientId: '410375819014-0ca6g3dq498tqb6mqacru68lpb8pv5h5.apps.googleusercontent.com',
    iosClientId: '410375819014-5tv371sd0ib3h84ka1q1movmmv7e6a17.apps.googleusercontent.com',
    iosBundleId: 'com.example.routinecareproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNixlZ23ed2qZ9_TyMyMDBQCNPOjdzB68',
    appId: '1:410375819014:web:4e658f51664609bdd3d887',
    messagingSenderId: '410375819014',
    projectId: 'workoutzzang-9b6f7',
    authDomain: 'workoutzzang-9b6f7.firebaseapp.com',
    storageBucket: 'workoutzzang-9b6f7.firebasestorage.app',
    measurementId: 'G-38D17340H1',
  );
}
